// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';
import 'package:meta_weather/model/source.dart';
import 'package:meta_weather/model/weather.dart';
part 'location.g.dart';
@JsonSerializable()
class Location {
  @JsonKey(name: 'consolidated_weather')
  List<Weather> consolidatedWeather;
  String time;
  @JsonKey(name: 'sun_rise')
  String sunRise;
  @JsonKey(name: 'sun_set')
  String sunSet;
  @JsonKey(name: 'timezone_name')
  String timezoneName;
  Location parent;
  List<Source> sources;
  String title;
  @JsonKey(name: 'location_type')
  String locationType;
  int woeid;
  @JsonKey(name: 'latt_long')
  String lattLong;
  String timezone;

  Location({
    this.consolidatedWeather,
    this.time,
    this.sunRise,
    this.sunSet,
    this.timezoneName,
    this.parent,
    this.sources,
    this.title,
    this.locationType,
    this.woeid,
    this.lattLong,
    this.timezone,
  });


  factory Location.fromJson(Map<String, dynamic> json) => _$LocationFromJson(json);
  Map<String, dynamic> toJson() => _$LocationToJson(this);
}



